# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=25, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('weigh_time', models.DateTimeField(auto_now_add=True, verbose_name='Weigh Time')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishingcontest.Contestant')),
            ],
        ),
    ]
